language: C

sudo:
  - required

os : 
  - linux 

dist :
#  - trusty
#  - xenial
 - bionic

branches :
  except :
    - /^WIP_.*/


compiler:
  - arm-linux-gnueabi-gcc-4.7 
  - arm-linux-gnueabi-gcc-5
  - arm-linux-gnueabi-gcc-6
  - arm-linux-gnueabi-gcc-7
  - arm-linux-gnueabi-gcc-8       
env:
  - DEFCONF=CPS-MC341-ADSCX.novlan_defconfig
  - DEFCONF=CPS-MC341-ADSCX.1lan_defconfig
  - DEFCONF=CPS-MC341-ADSCX.2lan_defconfig
  - DEFCONF=CPS-MC341-DSX.novlan_defconfig
  - DEFCONF=CPS-MC341-DSX.1lan_defconfig
  - DEFCONF=CPS-MC341-DSX.2lan_defconfig
  - DEFCONF=CPS-MC341-AX.novlan_defconfig
  - DEFCONF=CPS-MC341-AX.1lan_defconfig
  - DEFCONF=CPS-MC341-AX.2lan_defconfig
  - DEFCONF=CPS-MC341-DS1X.novlan_defconfig
  - DEFCONF=CPS-MC341-DS1X.1lan_defconfig
  - DEFCONF=CPS-MC341-DS1X.2lan_defconfig        
  - DEFCONF=CPS-MCS341-DSX.novlan_defconfig
  - DEFCONF=CPS-MCS341-DSX.1lan_defconfig
  - DEFCONF=CPS-MCS341-DSX.2lan_defconfig

before_install:
  # apt-get install
  - if [[ $TRAVIS_COMPILER = "arm-linux-gnueabi-gcc-8" ]];then GCC_COMP=gcc-8-arm-linux-gnueabi; fi
  - if [[ $TRAVIS_COMPILER = "arm-linux-gnueabi-gcc-7" ]];then GCC_COMP=gcc-7-arm-linux-gnueabi; fi
  - if [[ $TRAVIS_COMPILER = "arm-linux-gnueabi-gcc-6" ]];then GCC_COMP=gcc-6-arm-linux-gnueabi; fi
  - if [[ $TRAVIS_COMPILER = "arm-linux-gnueabi-gcc-5" ]];then GCC_COMP=gcc-5-arm-linux-gnueabi; fi
  - if [[ $TRAVIS_COMPILER = "arm-linux-gnueabi-gcc-4.7" ]];then GCC_COMP=gcc-4.7-arm-linux-gnueabi; fi
  - echo  "$GCC_COMP"
  - ls /etc/apt/
  - ls /etc/apt/sources.list.d/
  - cat /etc/apt/sources.list.d/pgdg.list
  - sudo apt-get install -y $GCC_COMP libncurses5-dev binutils-arm-linux-gnueabi u-boot-tools
  - export CROSS_COMPILE=arm-linux-gnueabi-
  - export ARCH=arm
  - sudo ln -s /usr/bin/$TRAVIS_COMPILER /usr/bin/arm-linux-gnueabi-gcc
  - export CPU_COUNT=`cat /proc/cpuinfo | grep -c processor`
  - export JOB_NUMBER=`expr $CPU_COUNT + 1`

script:
  - ls /usr/bin/arm* 
  # Test 
  - make distclean
  - make defconfig $DEFCONF
  - make prepare
  - make -j$JOB_NUMBER uImage
  - sudo make -j$JOB_NUMBER modules
  - sudo make -j$JOB_NUMBER modules_install
 
after_script:

